# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labordialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.txtEID = QtWidgets.QLineEdit(MainWindow)
        self.txtEID.setGeometry(QtCore.QRect(160, 60, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtEID.setFont(font)
        self.txtEID.setObjectName("txtEID")
        self.txtWOID = QtWidgets.QLineEdit(MainWindow)
        self.txtWOID.setGeometry(QtCore.QRect(160, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtWOID.setFont(font)
        self.txtWOID.setObjectName("txtWOID")
        self.lblClock = QtWidgets.QLabel(MainWindow)
        self.lblClock.setGeometry(QtCore.QRect(20, 70, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblClock.setFont(font)
        self.lblClock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClock.setObjectName("lblClock")
        self.lblWOID = QtWidgets.QLabel(MainWindow)
        self.lblWOID.setGeometry(QtCore.QRect(20, 120, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblWOID.setFont(font)
        self.lblWOID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOID.setObjectName("lblWOID")
        self.btnStart = QtWidgets.QPushButton(MainWindow)
        self.btnStart.setGeometry(QtCore.QRect(140, 170, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.btnStop = QtWidgets.QPushButton(MainWindow)
        self.btnStop.setGeometry(QtCore.QRect(140, 260, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.rbFab = QtWidgets.QRadioButton(MainWindow)
        self.rbFab.setGeometry(QtCore.QRect(390, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbFab.setFont(font)
        self.rbFab.setObjectName("rbFab")
        self.rbAssembly = QtWidgets.QRadioButton(MainWindow)
        self.rbAssembly.setGeometry(QtCore.QRect(390, 130, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbAssembly.setFont(font)
        self.rbAssembly.setObjectName("rbAssembly")
        self.rbWeld = QtWidgets.QRadioButton(MainWindow)
        self.rbWeld.setGeometry(QtCore.QRect(390, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbWeld.setFont(font)
        self.rbWeld.setObjectName("rbWeld")
        self.rbPaint = QtWidgets.QRadioButton(MainWindow)
        self.rbPaint.setGeometry(QtCore.QRect(390, 290, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbPaint.setFont(font)
        self.rbPaint.setObjectName("rbPaint")
        self.rbElectric = QtWidgets.QRadioButton(MainWindow)
        self.rbElectric.setGeometry(QtCore.QRect(390, 370, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbElectric.setFont(font)
        self.rbElectric.setObjectName("rbElectric")
        self.rbFinal = QtWidgets.QRadioButton(MainWindow)
        self.rbFinal.setGeometry(QtCore.QRect(560, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbFinal.setFont(font)
        self.rbFinal.setIconSize(QtCore.QSize(16, 16))
        self.rbFinal.setObjectName("rbFinal")
        self.rbLab = QtWidgets.QRadioButton(MainWindow)
        self.rbLab.setGeometry(QtCore.QRect(560, 370, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbLab.setFont(font)
        self.rbLab.setObjectName("rbLab")
        self.rbIndirect = QtWidgets.QRadioButton(MainWindow)
        self.rbIndirect.setGeometry(QtCore.QRect(560, 130, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbIndirect.setFont(font)
        self.rbIndirect.setObjectName("rbIndirect")
        self.rbShipReceive = QtWidgets.QRadioButton(MainWindow)
        self.rbShipReceive.setGeometry(QtCore.QRect(560, 210, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbShipReceive.setFont(font)
        self.rbShipReceive.setObjectName("rbShipReceive")
        self.rbMaterialHandling = QtWidgets.QRadioButton(MainWindow)
        self.rbMaterialHandling.setGeometry(QtCore.QRect(560, 290, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rbMaterialHandling.setFont(font)
        self.rbMaterialHandling.setObjectName("rbMaterialHandling")
        self.btnClear = QtWidgets.QPushButton(MainWindow)
        self.btnClear.setGeometry(QtCore.QRect(140, 350, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.lcdTime = QtWidgets.QLCDNumber(MainWindow)
        self.lcdTime.setGeometry(QtCore.QRect(160, 10, 131, 41))
        self.lcdTime.setObjectName("lcdTime")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Freeman Labor Tracker"))
        self.lblClock.setText(_translate("MainWindow", "Clock #"))
        self.lblWOID.setText(_translate("MainWindow", "WO #"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.rbFab.setText(_translate("MainWindow", "Fab"))
        self.rbAssembly.setText(_translate("MainWindow", "Assembly"))
        self.rbWeld.setText(_translate("MainWindow", "Weld"))
        self.rbPaint.setText(_translate("MainWindow", "Paint"))
        self.rbElectric.setText(_translate("MainWindow", "Electric"))
        self.rbFinal.setText(_translate("MainWindow", "Final"))
        self.rbLab.setText(_translate("MainWindow", "Lab"))
        self.rbIndirect.setText(_translate("MainWindow", "Indirect"))
        self.rbShipReceive.setText(_translate("MainWindow", "Ship/Receive"))
        self.rbMaterialHandling.setText(_translate("MainWindow", "Material Handling"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

